### ISSUE TITLE
Question about integrating with Docsy

### ISSUE THREAD

**Issue by onknows** [hugomods/search#122] opened 2023-05-04 05:50 UTC
I don't think the documentation and example project is enough to be able to integrate search into an existing website. 

The current viable path seems to be to copy the example site and build on that. 

My path is to integrate search into a Hugo website with Docsy theme. That, I think, is not possible. 

I posted question on Stackoverflow but I don't expect an answer there.

https://stackoverflow.com/questions/76169755/how-to-use-hugo-icons-modules-and-fix-cant-evaluate-field-vendors-in-type-str

I you can help me fix this I will provide you with a Dutch translation for https://github.com/hugomods/search/issues/122#issue-1695302677

**Comment by razonyang** [comment] 2023-05-04 08:49
Thanks for being interested in this, the error was caused by the Bootstrap's config, I made a [PR](https://github.com/google/docsy/pull/1509) for Docsy, will provide a working example after the patch was merged.

**Comment by razonyang** [comment] 2023-05-06 05:51
Integrate guide: https://hugomods.com/en/blog/2023/05/integrate-docsy-with-the-search-module/.

You don't have to wait for the patch to be merged, but you'll need to pay attention to the sequence of imported modules (the guide has mentioned this).

**Closed by razonyang** 2023-05-06 05:51 UTC
Labels: documentation, good first issue
